.gitignore, CONTRIBUTING.md
Wanted to get these in place right away, will consider instructions for developing in VS Code and Intellij later, though I'm thinking those might be better off on our Wiki and not being specific to a project.
=> Couple CONTRIB improvements

marklogic/documents.py, tests/test_read_documents.py, tests/test_write_documents.py, tests/test_write_documents_with_metadata.py
- Allowing for a single Document to be written without an array
- Allowing for a single Document to be read without using an array
- Filled in a "TODO" test
- Decoding the content into a string if it's of a certain type
=> Small improvements and fixes

docs/getting-started.md, docs/index.md, docs/managing-documents/managing-documents.md, docs/managing-documents/reading.md, docs/managing-documents/searching.md, docs/managing-documents/writing.md, marklogic/documents.py, poetry.lock, pyproject.toml, tests/test_search_docs.py
Couple small code changes:
- `Document` now has a useful overriden "repr" method, along with a `metadata` getter for inspection purposes.
- Moved `q` to be the first arg for `search` so that a user doesn't have to type "q=" for the common use case of specifying a search string.
=> DEVEXP-514 Added docs for reading, writing, and searching

docs/managing-documents/reading.md, docs/managing-documents/searching.md
They weren't working if you went through the reading examples first.
=> Making the search docs examples work

marklogic/client.py, marklogic/rows.py, test-app/src/main/ml-config/databases/content-database.json, test-app/src/main/ml-config/databases/modules-database.json, test-app/src/main/ml-config/databases/schemas-database.json, test-app/src/main/ml-data/collections.properties, test-app/src/main/ml-data/musicians/collections.properties, test-app/src/main/ml-data/musicians/musician1.json, test-app/src/main/ml-data/musicians/musician2.json, test-app/src/main/ml-data/musicians/musician3.json, test-app/src/main/ml-data/musicians/musician4.json, test-app/src/main/ml-data/musicians/permissions.properties, test-app/src/main/ml-schemas/tde/musician.json, tests/test_graphql.py, tests/test_read_documents.py, tests/test_search_docs.py
One thing I didn't do, but maybe should have: change the tests that use the "test-data" collection for searching, etc. My thought is that we use a different collection for searching and put the "test-data" collection on all data.
=> DEVEXP-575: Submit GraphQL query with Python client

marklogic/transactions.py, tests/test_transactions.py
=> Improved error for when transaction cannot be completed

marklogic/rows.py, tests/test_graphql.py, tests/test_rows.py
Also renamed "test_query.py" to "test_rows.py" to align with the other tests.
No functional changes here, just formatting.
=> Formatted rows.py and its tests

marklogic/rows.py, tests/test_graphql.py
This seems more expected to a user, who can now use a single function and select the type of query they want to submit.
=> Merged `graphql` function into `query` function.

docs/example-setup.md, docs/managing-documents/managing-documents.md, docs/rows.md, docs/transactions.md, shell/docs.py, shell/test_app.py, test-app/src/main/ml-config/security/users/python-docs-user.json
Will tackle eval in a separate PR, had a lot to add with this one.
=> DEVEXP-589 Added docs for rows feature

docs/eval.md, docs/example-setup.md, docs/transactions.md, marklogic/client.py, test-app/src/main/ml-config/security/roles/python-docs-role.json, test-app/src/main/ml-config/security/users/python-docs-user.json, tests/test_eval.py
Tossed in a couple more test cases. Curiously could not find a way to return a "binary()" with it being associated with a URI.
=> DEVEXP-589 Added eval docs

docs/eval.md, marklogic/internal/eval.py, tests/test_eval.py
Also moved the primitive_value_converters below the main public function.
=> Added impl and test for non-document binary()

marklogic/client.py, marklogic/internal/eval.py, marklogic/rows.py, tests/test_eval.py, tests/test_rows.py
This seems like the right choices for v1/rows, where a JSON object is returned by default. For eval, an "empty sequence" is different from an "empty array" - an empty array is something that still exists (an array with no items in it) - and so when an empty sequence is returned for eval/invoke, None seems more appropriate too.
=> Returning None instead of empty array

docs/creating-client.md, docs/eval.md, docs/managing-documents/reading.md, docs/managing-documents/searching.md, docs/managing-documents/writing.md, docs/rows.md, docs/transactions.md
The main thing is the kwargs info for eval/rows; it looks like we'll have to add that to each page, as if it's in one place, it'll be easily missed. 
Added a TOC as well to make the pages nicer.
=> Added TOC and info on kwargs for eval/rows

.vscode/settings.json, CONTRIBUTING.md
=> Update the linting and formatting settings.

tests/test_rows_update.py
Was causing /doc1.json to be removed, thus affecting other tests.
=> Fixing Optic update test

CONTRIBUTING.md, marklogic/documents.py, pyproject.toml, test-app/.gitignore, test-app/docker-compose.yml, test-app/src/main/ml-data/doc2;copy.xml, test-app/src/main/ml-data/doc2=copy.xml, tests/test_search_docs.py
Python Client throws error when "filename" is not returned in response from the REST Api.
=> Fixes the bug identified in https://progresssoftware.atlassian.net/browse/MLE-14411

docs/creating-client.md
This ensures that if someone searches on "certificate" instead of "SSL", they'll find this section.
=> Adding the word "certificate" to the SSL docs

examples/langchain/README.md, examples/langchain/docker-compose-12.yml, examples/langchain/load_data_with_embeddings.py, examples/langchain/src/main/ml-config/databases/content-database.json, examples/langchain/src/main/ml-config/databases/schemas-database.json, examples/langchain/src/main/ml-schemas-12/tde/agents.json
This is just a start to be able to create an example and a Quick Start. Those will come next.
For now, this includes:
TDE for Optic vectors,
Docket compose for MarkLogic 12 (internal),
Script to load data with embeddings.
=> Adding setup for MarkLogic 12 examples

docs/creating-client.md, marklogic/cloud_auth.py
Can't rename the MarkLogicCloudAuth class, as that would be a breaking change.
=> Renamed to Progress Data Cloud

marklogic/vectors.py, test-app/docker-compose.yml, tests/test_vectors.py
Implements utilities for encoding and decoding vectors to/from base64 strings, mirroring MarkLogic's `vec:base64-encode` and `vec:base64-decode` functions.
- Enables interoperability between Python and MarkLogic for vector data.
- Includes tests to verify encoding and decoding functionality in Python and against a MarkLogic server.
80% Copilot generated. I just had to fix the tests that send requests to MarkLogic.
=> MLE-22708 - Adds vector encoding/decoding utilities

.editorconfig, .github/copilot-instructions.md
Sets up consistent code style and guidelines:
- Introduces EditorConfig to enforce consistent code formatting across the project.
- Provides Copilot instructions to guide AI code completion and generation, ensuring adherence to project standards, best practices, and dependency management.
=> MLE-12345 - Adds EditorConfig and Copilot Instructions

marklogic/vectors.py, tests/test_vectors.py
Refactors the vector encoding and decoding functions to be standalone functions instead of methods within a class.
This change improves code organization and potentially simplifies usage by removing the need to instantiate a utility class.
=> MLE-12345 - Refactors vector utility functions

docs/managing-documents/writing.md
=> MLE-23398 Added docs for vector functions

Jenkinsfile, test-app/.env, test-app/docker-compose.yml
Need to use the latest 12 image so that the vector tests pass.
=> MLE-23398 Trying to fix Jenkins
